resources:
  #- mysql-secret.yaml
- mysql-sealedsecret.yaml
- mysql-pv.yaml
- mysql-pvc.yaml
- mysql-service.yaml
- mysql-statefulset.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
