resources:
- laravel-deployment.yaml
- laravel-service.yaml
- nginx-configmap.yaml
- laravel-secrets.yaml
- mysql-secret.yaml
- retain-sc.yaml
- mysql-pv.yaml
- mysql-pvc.yaml
- mysql-service.yaml
- mysql-statefulset.yaml
- redis-configmap.yaml
- retain-redis-sc.yaml
- redis-pv.yaml
- redis-pvc.yaml
- redis-service.yaml
- redis-secret.yaml
- redis-statefulset.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
